export enum EnumStorageKeys {
	IS_AGREE_WITH_COOKIES = "HONEY_PARADISE_IS_AGREE_WITH_COOKIES",
	THEME_MODE = "HONEY_PARADISE_THEME_MODE",
	LANGUAGE = "HONEY_PARADISE_LOCALE_LANGUAGE",
	CURRENT_EMAIL = "HONEY_PARADISE_CURRENT_EMAIL",
	SESSION = "session",
}

export enum EnumSessionStorageKeys {
	CHANGE_PASSWORD_MODAL = "CHANGE_PASSWORD_MODAL",
}
