export enum EnumAuthTokens {
	ACCESS_TOKEN = "accessToken",
	REFRESH_TOKEN = "refreshToken",
}

export enum EnumStorageTokens {
	IS_AGREE_WITH_COOKIES = "HONEY_PARADISE_IS_AGREE_WITH_COOKIES",
	THEME_MODE = "HONEY_PARADISE_THEME_MODE",
	LANGUAGE = "HONEY_PARADISE_LOCALE_LANGUAGE",
}
