export const queryKeys = {
	getMyAccount: "get current account",
	getAllUserNotifications: "get all notifications",
	getUniqueFiledStatus: "get unique filed status",
	getAllProviders: "get all user providers",
	getUserSessions: "get all user sessions",
	getCurrentSession: "get current user session",
	getTelegramInfo: "get user telegram info",
	getMyCart: "get current user cart",
	getAllCatsWithProducts: "get all categories with products",
	getProductsBySearch: "get products by searching",
	getPopularProducts: "get popular products",
	getProductsByCategory: "get products by category slug",
	getAllOrders: "get all user's orders",
	getFavoriteProducts: "get all user's favorite products",
	getRecentViewedProducts: "get recent viewed products",
	getProductsRating: "get products rating",
	getProductsReviews: "get products reviews",
	getProductPage: "get product page data",
	getReviewComments: "get review's comments",

	recoverPassword: "account recover password",
	connectTg: "account connect telegram",
	disconnectTg: "account disconnect telegram",

	createAccount: "account create",
	createOrder: "create order",
	createProductReview: "create product review",
	createReviewComment: "create review comment",

	sendRecoverPasswordCode: "send password recover code",
	sendVerificationCode: "send email verification code",
	sendTfaCode: "send tfa sign in code",

	verifyEmail: "verify account email",
	verifyTfaCode: "verify tfa code",

	updateEmail: "update account email",
	updateNotificationsSettings: "update notifications settings",
	updatePassword: "update account password",
	updateProfileAvatar: "update profile avatar",
	updateProfile: "update profile",
	updateProfileSettings: "update profile settings",
	updateCartItemQuantity: "update cart item quantity",
	updateAvatarFrame: "update profile avatar frame",
	updateProductReview: "update product review",
	uploadUserSettings: "upload user settings file",

	logout: "logout",
	signIn: "sign in",
	telegramSignIn: "sign in with telegram",
	cancelTelegramSignIn: "cancel signing in with telegram",

	deleteNotifications: "delete selected notifications",
	deleteProfileAvatar: "delete profile avatar",
	deleteProvider: "delete user provider",
	deleteSession: "delete user session",
	deleteAllSessions: "delete all user sessions",
	deleteCartItem: "delete cart item",
	deleteProductReview: "delete product review",
	clearSession: "clear current cookie session",
	clearAllCart: "clear all cart items",
	clearAllFavoritesProducts: "clear all user favorites products",

	addCartItem: "add item to cart",
	addFavoritesToCart: "add favorite products to cart",

	markNotificationAsRead: "mark notification as read",
	markNotificationAsArchived: "mark all notifications as read",
	markAllNotificationAsRead: "mark notification as archived",

	switchFavoritesProducts: "switch user favorites products",
	reactToReview: "react to a review",
	usePromoCode: "use promo code",
	translateReview: "translate review or comment",
	replyToComment: "reply to a comment"
} as const
