services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 4200:4200
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - honey-paradise-backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - honey-paradise-backend

volumes:
  postgres_data:
  redis_data:

networks:
  honey-paradise-backend:
