/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type CreateUserDtoGender = typeof CreateUserDtoGender[keyof typeof CreateUserDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
