/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { GetMyNotificationResponse } from './getMyNotificationResponse';

export interface GetAllNotificationsResponse {
  notifications: GetMyNotificationResponse[];
  length: number;
  unReadLength: number;
}
