/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { GetAllConnectionsResponseType } from './getAllConnectionsResponseType';

export interface GetAllConnectionsResponse {
  id: string;
  providerId: string;
  type: GetAllConnectionsResponseType;
  userId: string;
  createdAt: string;
  updatedAt: string;
}
