/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type GetMyNotificationResponseType = typeof GetMyNotificationResponseType[keyof typeof GetMyNotificationResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMyNotificationResponseType = {
  ORDER_STATUS: 'ORDER_STATUS',
  ACCOUNT_STATUS: 'ACCOUNT_STATUS',
  SPECIAL_OFFERS: 'SPECIAL_OFFERS',
  TELEGRAM: 'TELEGRAM',
} as const;
