/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { GetMyNotificationResponseType } from './getMyNotificationResponseType';

export interface GetMyNotificationResponse {
  id: string;
  message: string;
  type: GetMyNotificationResponseType;
  isRead: boolean;
  createdAt: string;
  updatedAt: string;
}
