/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export interface GetMyCartItemsResponse {
  id: string;
  /** Quantity of the products */
  priceInUSD: number;
  /** Price of the product */
  quantity: number;
  createdAt: string;
  updatedAt: string;
}
