/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { GetMeResponseRole } from './getMeResponseRole';
import type { GetMeResponseGender } from './getMeResponseGender';
import type { GetMySettingsResponse } from './getMySettingsResponse';
import type { GetMyNotificationsSettingsResponse } from './getMyNotificationsSettingsResponse';

export interface GetMeResponse {
  id: string;
  role: GetMeResponseRole;
  isVerified: boolean;
  isTFAEnabled: boolean;
  username: string;
  email: string;
  /** @nullable */
  phoneNumber: string | null;
  /** @nullable */
  telegramId: string | null;
  gender: GetMeResponseGender;
  avatarPath: string;
  /** @nullable */
  birthdate: string | null;
  settings: GetMySettingsResponse;
  notificationSettings: GetMyNotificationsSettingsResponse;
  createdAt: string;
  updatedAt: string;
}
