/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type GetMeResponseRole = typeof GetMeResponseRole[keyof typeof GetMeResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMeResponseRole = {
  REGULAR: 'REGULAR',
  VIP: 'VIP',
  MANAGER: 'MANAGER',
  DELIVERANCE: 'DELIVERANCE',
  ADMIN: 'ADMIN',
} as const;
