/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type GetMyCartResponseCurrency = typeof GetMyCartResponseCurrency[keyof typeof GetMyCartResponseCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMyCartResponseCurrency = {
  RUBLE: 'RUBLE',
  DOLLAR: 'DOLLAR',
  EURO: 'EURO',
} as const;
