/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { GetMyCartResponseCurrency } from './getMyCartResponseCurrency';
import type { GetMyCartItemsResponse } from './getMyCartItemsResponse';

export interface GetMyCartResponse {
  id: string;
  currency: GetMyCartResponseCurrency;
  length: number;
  totalPrice: number;
  cartItems: GetMyCartItemsResponse[];
  createdAt: string;
  updatedAt: string;
}
