/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type UpdateUserSettingsDtoDefaultTheme = typeof UpdateUserSettingsDtoDefaultTheme[keyof typeof UpdateUserSettingsDtoDefaultTheme];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserSettingsDtoDefaultTheme = {
  DARK: 'DARK',
  LIGHT: 'LIGHT',
} as const;
