/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */
import type { UpdateUserSettingsDtoDefaultLanguage } from './updateUserSettingsDtoDefaultLanguage';
import type { UpdateUserSettingsDtoDefaultTheme } from './updateUserSettingsDtoDefaultTheme';

export interface UpdateUserSettingsDto {
  defaultLanguage?: UpdateUserSettingsDtoDefaultLanguage;
  defaultTheme?: UpdateUserSettingsDtoDefaultTheme;
  useFullLogout?: boolean;
  isTFAEnabled?: boolean;
  useTgTfaLogin?: boolean;
}
