/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Honey Paradise
 * Honey Paradise API
 * OpenAPI spec version: 0.0.2
 */

export type UpdateUserSettingsDtoDefaultLanguage = typeof UpdateUserSettingsDtoDefaultLanguage[keyof typeof UpdateUserSettingsDtoDefaultLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserSettingsDtoDefaultLanguage = {
  ru: 'ru',
  en: 'en',
} as const;
